In [ ]:
# import sys
# !{sys.executable} -m pip uninstall prettytable -y
# !{sys.executable} -m pip uninstall ipython-sql -y
# !{sys.executable} -m pip install prettytable==3.9.0
# !{sys.executable} -m pip install ipython-sql==0.4.1

In [ ]:
# !pip uninstall sqlalchemy -y
# !pip install sqlalchemy==1.4.49

In [2]:
%load_ext sql

In [3]:
%config SqlMagic.autopandas = True
%config SqlMagic.displaycon = False

In [4]:
import sys
print(sys.executable)

f:\Python\FastAPI01\myenv\Scripts\python.exe

In [5]:
import os

In [6]:
host = os.getenv('SQL_HOST', 'localhost')
port = os.getenv('SQL_PORT', '5432')
user = os.getenv('SQL_USER')
password = os.getenv('SQL_PASSWORD')
database = os.getenv('SQL_DB', 'gis_sql')

In [7]:
connection_string = f"postgresql://{user}:{password}@{host}:{port}/{database}"

In [8]:
from sqlalchemy import create_engine

engine = create_engine(connection_string)

In [10]:

%sql $connection_string

In [11]:
%%sql 
SELECT * FROM us_cities LIMIT 5;

5 rows affected.

    id  POP_2010            ELEV_IN_FT STATE Ele_m
0   53     40888  1611.000000000000000    ND  None
1  101     52838   830.000000000000000    ND  None
2  153     15427  1407.000000000000000    ND  None
3  177    105549   902.000000000000000    ND  None
4  192     17787  2411.000000000000000    ND  None

In [14]:
%%sql
SELECT * FROM us_cities WHERE "POP_2010" > 1000000;

13 rows affected.

       id  POP_2010  ELEV_IN_FT STATE Ele_m
0     494   2695598     2695598    IL  None
1     673   1526006     1526006    PA  None
2    8329   8175133     8175133    NY  None
3   19441   1197816     1197816    TX  None
4   20492   3792621     3792621    CA  None
5   20569   1445632     1445632    AZ  None
6   20926   2099451     2099451    TX  None
7   21991   1307402     1307402    CA  None
8   22221   1327407     1327407    TX  None
9   38126   1408473     1408473    NY  None
10  38127   1619090     1619090    NY  None
11  38128   2565635     2565635    NY  None
12  38129   2272771     2272771    NY  None