In [ ]:
# import sys
# !{sys.executable} -m pip uninstall prettytable -y
# !{sys.executable} -m pip uninstall ipython-sql -y
# !{sys.executable} -m pip install prettytable==3.9.0
# !{sys.executable} -m pip install ipython-sql==0.4.1

In [ ]:
# !pip uninstall sqlalchemy -y
# !pip install sqlalchemy==1.4.49

In [15]:
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [16]:
%config SqlMagic.autopandas = True
%config SqlMagic.displaycon = False

In [17]:
import sys
print(sys.executable)

f:\Python\FastAPI01\myenv\Scripts\python.exe

In [18]:
import os

In [19]:
host = os.getenv('SQL_HOST', 'localhost')
port = os.getenv('SQL_PORT', '5432')
user = os.getenv('SQL_USER')
password = os.getenv('SQL_PASSWORD')
database = os.getenv('SQL_DB', 'sdb')

In [20]:
connection_string = f"postgresql://{user}:{password}@{host}:{port}/{database}"

In [21]:
from sqlalchemy import create_engine

engine = create_engine(connection_string)

In [22]:

%sql $connection_string

In [28]:
%%sql
SELECT * FROM nyc_neighborhoods WHERE FALSE

0 rows affected.

Empty DataFrame
Columns: []
Index: []

In [24]:
%%sql 
SELECT * FROM nyc_neighborhoods LIMIT 5;

5 rows affected.

,id,geom,boroname,name
0,1,0106000020266900000100000001030000000100000011...,Brooklyn,Bensonhurst
1,2,0106000020266900000100000001030000000100000008...,Manhattan,East Village
2,3,0106000020266900000100000001030000000100000034...,Manhattan,West Village
3,4,0106000020266900000100000001030000000100000057...,The Bronx,Throggs Neck
4,5,0106000020266900000100000001030000000100000066...,The Bronx,Wakefield-Williamsbridge

In [26]:
%%sql
SELECT * FROM nyc_neighborhoods WHERE boroname LIKE '%Manhattan%';

28 rows affected.

,id,geom,boroname,name
0,2,0106000020266900000100000001030000000100000008...,Manhattan,East Village
1,3,0106000020266900000100000001030000000100000034...,Manhattan,West Village
2,7,010600002026690000010000000103000000010000001F...,Manhattan,Battery Park
3,8,0106000020266900000100000001030000000100000006...,Manhattan,Carnegie Hill
4,11,0106000020266900000100000001030000000100000017...,Manhattan,Harlem
5,12,0106000020266900000100000001030000000100000016...,Manhattan,Gramercy
6,22,0106000020266900000100000001030000000100000012...,Manhattan,Soho
7,30,010600002026690000010000000103000000010000000C...,Manhattan,Morningside Heights
8,31,0106000020266900000100000001030000000100000007...,Manhattan,Murray Hill
9,48,010600002026690000010000000103000000010000000D...,Manhattan,Central Park
10,55,010600002026690000010000000103000000010000000D...,Manhattan,Greenwich Village
11,56,010600002026690000010000000103000000010000002B...,Manhattan,Midtown
12,68,010600002026690000010000000103000000010000001D...,Manhattan,Tribeca
13,69,0106000020266900000100000001030000000100000006...,Manhattan,North Sutton Area
14,73,0106000020266900000100000001030000000100000011...,Manhattan,Upper East Side
15,74,010600002026690000010000000103000000010000003E...,Manhattan,Financial District
16,75,010600002026690000010000000103000000010000002C...,Manhattan,Inwood
17,78,0106000020266900000100000001030000000100000018...,Manhattan,Lower East Side
18,79,0106000020266900000100000001030000000100000040...,Manhattan,Chelsea
19,89,0106000020266900000100000001030000000100000017...,Manhattan,Washington Heights
20,90,0106000020266900000100000001030000000100000010...,Manhattan,Upper West Side
21,95,010600002026690000010000000103000000010000002C...,Manhattan,Clinton
22,107,0106000020266900000100000001030000000100000007...,Manhattan,Garment District
23,108,010600002026690000010000000103000000010000000B...,Manhattan,East Harlem
24,115,0106000020266900000100000001030000000100000007...,Manhattan,Little Italy
25,117,0106000020266900000100000001030000000100000012...,Manhattan,Hamilton Heights
26,120,010600002026690000010000000103000000010000000A...,Manhattan,Yorkville
27,121,0106000020266900000100000001030000000100000009...,Manhattan,Chinatown

In [30]:
%%sql
SELECT avg(char_length(name)), stddev(char_length(name)) 
FROM nyc_neighborhoods
WHERE boroname = 'Manhattan';

1 rows affected.

                   avg              stddev
0  11.8214285714285714  4.3123729948325257

In [31]:
%%sql
SELECT avg(char_length(name)), stddev(char_length(name)) 
FROM nyc_neighborhoods
GROUP BY boroname;

5 rows affected.

                   avg              stddev
0  11.6666666666666667  5.0057438272815975
1  11.7391304347826087  3.9105613559407395
2  12.2916666666666667  5.2043390480959474
3  12.0416666666666667  3.6651017740975152
4  11.8214285714285714  4.3123729948325257